### ISSUE TITLE
[bug] HCloud Firewall resource created even if all firewall properties disabled

### ISSUE THREAD

**Issue by mgerasimchuk** [hcloud-k8s/terraform-hcloud-kubernetes#19]
**Step to reproduce:**
- firewall_use_current_ipv4 = false
- firewall_use_current_ipv6 = false

**Expected behavior:**
- hcloud firewall not created

**Actual behavior:**
- hcloud firewall created (with no rules but with all hcloud servers in it)
- kube API server doesn't reachable
- tf apply process finished with error

**Workaround:**
- remove firewall through the hetzner panel during the tf apply process

**Comment by M4t7e** [comment]
Actually this behavior is intentional and not a bug. This module is designed to always create a firewall to prevent the unwanted exposure of endpoints. This is also crucial because Talos accepts initial bootstrap API calls from any source. During the initial cluster creation or when resetting Talos nodes, it's possible for unauthorized users to take control of the nodes if they are not protected by a firewall. Additionally, it is essential for security to keep other ports closed to the public by default. You can view the exposed ports using the command `talosctl netstat -lp`.

I've included some firewall configuration examples in the [Advanced Configuration](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes#hammer_and_pick-advanced-configuration) section. Please ensure you are using version [0.6.2](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/releases/tag/0.6.2) or later, as earlier versions used incorrect data types.

**Comment by mgerasimchuk** [comment]
Thank you for the detailed description, got the idea now!

upd:
as a result, migrated to this config to make my cluster+talos apis  publically available from any IPs:
```
  firewall_use_current_ipv4 = false
  firewall_use_current_ipv6 = false
  firewall_extra_rules = [
    {
      description = "Allow Incoming Requests to Kube API from any IPv4/IPv6"
      direction   = "in"
      source_ips = ["0.0.0.0/0", "::/0"]
      protocol    = "tcp"
      port        = "6443"
    },
    {
      description = "Allow Incoming Requests to Talos API from any IPv4/IPv6"
      direction   = "in"
      source_ips = ["0.0.0.0/0", "::/0"]
      protocol    = "tcp"
      port        = "50000"
    }
  ]
  ```
