### ISSUE TITLE
Cluster name must be no longer than 16 characters

### ISSUE THREAD

**Issue by lpellegr** [hcloud-k8s/terraform-hcloud-kubernetes#26]
> │ Error: Invalid value for variable
> │ 
> │   on kubernetes.tf line 5, in module "kubernetes":
> │    5:     cluster_name = "my-cluster-name-is-quite-long"
> │     ├────────────────
> │     │ var.cluster_name is "my-cluster-name-is-quite-long"
> │ 
> │ The cluster name must start and end with a lowercase letter or number, can contain hyphens, and must be no longer than 16 characters.
> │ 
> │ This was checked by the validation rule at .terraform/modules/kubernetes/variables.tf:6,3-13.

Is there a technical reason for restricting the cluster name to 16 characters?

**Comment by M4t7e** [comment]
The 16-character limit isn’t strictly necessary from a technical perspective but is related to the 63-character length constraint for Kubernetes and Hetzner Cloud labels. The `cluster_name` is often embedded in resource names and labels, so keeping it short helps avoid hitting those limits. Also, since `cluster_name` is almost immutable, it’s important to set a practical value upfront to prevent disruptive changes later. While increasing the limit to 24 or 32 characters could work, I wouldn’t recommend going higher. 

Honestly, I didn’t expect users to choose such long names, as it also increases the length of all associated resource names, which can make them harder to work with. Do you actually need it?

**Comment by laurentpellegrino** [comment]
Thanks for the explanation. 

Yes, I exceeded the limit three times across four deployments. A 16-character limit is quite restrictive. Increasing it to 32 would provide significantly more flexibility, particularly when managing multiple clusters and needing to add distinguishing suffixes.

**Comment by M4t7e** [comment]
@lpellegr The limit has been increased to 32 in [0.8.1](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/releases/tag/0.8.1)
